apiVersion: batch/v1
kind: CronJob
metadata:
  name: dice
spec:
  jobTemplate:
    metadata:
      name: dice
    spec:
      completions: 1
      backoffLimit: 25
      activeDeadlineSeconds: 20
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: throw-dice
              name: dice
              resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
