apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv #👈👈👈 Change
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi #👈👈👈 Change
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/my-host" #👈👈👈 Change

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc #👈👈👈 Change
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi #👈👈👈 Change


---

apiVersion: v1
kind: Pod
metadata:
  name: storage-pod #👈👈👈 Change
spec:
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc #👈👈👈 Change
  containers:
    - name: my-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/my-mount" #👈👈👈 Change
          name: my-volume